### ISSUE TITLE
Missing error/warning when signing message on wrong chain

### ISSUE THREAD

**Issue by aloisklink** [poap-xyz/poap-fun#51]
Hiya, first of all, I love poap.fun, it's a beautiful website.

I just tried to press "Join Raffle" only to have Metamask immediately pop-up and crash, due to being on the xDAI chain instead of the Ethereum mainnet.

There unfortunately doesn't seem to be any sort of warning/error message about this, I only realised what was going on when I opened up the JavaScript console.

The error I'm getting in my JavaScript console is the following `MetaMask - RPC Error: Provided chainId "1" must match the active chainId "137" `:

```yaml
code: -32603
data:
originalError: {name: "AssertionError", actual: 1, expected: 137, operator: "==", message: "Provided chainId "1" must match the active chainId "137"", …}
__proto__: Object
message: "Provided chainId \"1\" must match the active chainId \"137\""
```
